# Generated by Django 4.2.1 on 2023-05-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='responsibles',
            field=models.ManyToManyField(related_name='staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
            preserve_default=False,
        ),
    ]
