# Generated by Django 4.1.7 on 2023-05-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_photo_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/account_pdp'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('IP', 'In Progress'), ('IR', 'In Review'), ('CL', 'Cancelled'), ('P', 'Pending')], max_length=2),
        ),
    ]
