# Generated by Django 4.2.1 on 2023-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CL', 'Cancelled'), ('IP', 'In Progress'), ('C', 'Completed'), ('IR', 'In Review'), ('P', 'Pending')], max_length=2),
        ),
    ]
