# Generated by Django 4.1.7 on 2023-05-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CL', 'Cancelled'), ('P', 'Pending'), ('IR', 'In Review'), ('C', 'Completed')], max_length=2),
        ),
    ]
