# Generated by Django 4.1.7 on 2023-05-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/account_pdp'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('IR', 'In Review'), ('P', 'Pending'), ('IP', 'In Progress'), ('CL', 'Cancelled')], max_length=2),
        ),
    ]
