# Generated by Django 4.1.7 on 2023-05-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_client_photo_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('IP', 'In Progress'), ('IR', 'In Review'), ('CL', 'Cancelled')], max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/services'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='in_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
