# Generated by Django 4.2.1 on 2023-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_project_image_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('IP', 'In Progress'), ('IR', 'In Review'), ('CL', 'Cancelled')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='staff',
            name='in_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/', null=True),
        ),
    ]
